name: Testing Greeting Kata
run-name: ${{ github.actor }} is testing Greeting Kata
on: push
jobs:
    build_and_test_job:
        name: Build and Test Greeting Kata
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0.x'
            - name: Restore NuGet dependencies
              run: dotnet restore
            - name: Build solution
              run: dotnet build
            - name: Run tests
              run: dotnet test
            - name: Create NuGet package
              run: dotnet pack --configuration Release /p:PackageVersion=1.0.${{ github.run_number }}
            - name: Push NuGet package
              run: |
                dotnet nuget add source \
                  --username pausig \
                  --password  ${{ secrets.TOKEN }} \
                  --store-password-in-clear-text \
                  --name github "https://nuget.pkg.github.com/pausig/index.json"
                
                dotnet nuget push "GreetingCICD/bin/Release/GreetingCICD.1.0.${{ github.run_number }}.nupkg" \
                  --api-key ${{ secrets.TOKEN }} \
                  --source "github"